#!/usr/bin/env bash
# Manages the script manage_my_process.
# 	When passed the argument `start`:
# 	 * Starts manage_my_process
# 	 * Creates a file containings its PID in /var/run/my_process.pid
# 	 * Displays "manage_my_process started"
# 	When passed the argument `stop`:
# 	 * Stops manage_my_process
# 	 * Deletes the file /var/run/my_process.pid
# 	 * Displays "manage_my_process stopped"
# 	When passed the argument `restart`:
# 	 * Stops manage_my_process
# 	 * Deletes the file /var/run/my_process.pid
# 	 * Starts manage_my_process
# 	 * Creates a file containing its PID in /var/run/my_process.pid
# 	 * Displays "manage_my_process restarted"
# 	If any other or no arguments are passed, displays
# 	- "Usage: manage_my_process {start|stop|restart}"

arg1="$1"

case "$arg1" in

	start)
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process started"
		;;
	stop)
		sudo pkill -f "./manage_my_process"
		rm /var/run/my_process.pid
		echo "manage_my_process stopped"
		;;
	restart)
		sudo pkill -f "./manage_my_process"
		rm /var/run/my_process.pid
		./manage_my_process &
		echo $$ > /var/run/my_process.pid
		echo "manage_my_process restarted"
		;;
	*)
		echo "Usage: manage_my_process {start|stop|restart}"
		;;
esac
