#!/usr/bin/env bash
# Runs infinitely with a timeout of 2 seconds
# Ignores SIGTERM termination signal

i=1

while (( i > 0 ))
do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
