#!/usr/bin/env bash
# Reads the "/etc/passwd" file outputs a generated story

file="/etc/passwd"

while IFS=":" read -r user pwd uid gid info homedir shell;
do
	echo "The user $user is part of the $gid gang, lives in $homedir and \
rides $shell. $uid's place is protected by the passcode $pwd, \
more info about the user here: $info"
done < "$file"
