#!/usr/bin/env bash
# This script displays "Best School" 9 times and "Hi" on the 9th iteration

i=0

while (( i < 10 ))
do
	if (( i == 3 )); then
		echo "bad luck"
	elif (( i == 7 )); then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( i++ ))
done
