#!/usr/bin/env bash
# setup Nginx to run as the "nginx" user
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
chmod 755 /etc/nginx/nginx.conf
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
pkill apache2
sudo -u nginx service nginx start
